INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (8, 'Leopard 2')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (8, 'M577A2')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (8, 'M113 BGM-71 TOW')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (8, 'Pandur II')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (9, 'Unimog 1750L')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (9, 'MAN KAT1')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (9, 'Iveco 90.17 WM')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (9, 'DAF Trucks YA 4440 D')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (10, 'MQM-170A Outlaw')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (10, 'Tekever AR4')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (11, 'NRP Arpão')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (11, 'NRP Tridente')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (12, 'NRP Hidra')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (13, 'NRP Vasco da Gama')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (13, 'NRP Corte-Real')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (14, 'EH101 Merlin')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (14, 'AgustaWestland AW119 Koala')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (15, 'F-16 Fighting Falcon')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (16, 'C-130 Hercules')
INSERT INTO EXERCITO.tipo_veiculo (maintipo, modelo) VALUES (16, 'CASA C-295')

SELECT * FROM EXERCITO.tipo_veiculo