INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Pistola')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Submetralhadora')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Espingarda')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Espingarda de Precisão')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Caçadeira')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Metralhadora')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Lança Granadas')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Tanque')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Camião tático')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Drone')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Submarino')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Lancha')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Fragata')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Helicóptero')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Caça')
INSERT INTO EXERCITO.tipo_equipamento (tipo) VALUES ('Transporte')