/*
*	RETORNA 0 SE MILITAR DE nCC JA EXISTE EM SOLDADO
*	MEDICO OU ENGENHEIRO
*/
ALTER FUNCTION EXERCITO.disjointMilitar (@nCC INT)
RETURNS BIT
AS
BEGIN
	IF EXISTS (SELECT * FROM EXERCITO.soldado WHERE nCC = @nCC)
	OR EXISTS (SELECT * FROM EXERCITO.medico WHERE nCC = @nCC)
	OR EXISTS (SELECT * FROM EXERCITO.engenheiro WHERE nCC = @nCC)
		BEGIN
			RETURN 0
		END
	RETURN 1
END
GO

SELECT * FROM EXERCITO.equipamento
SELECT * FROM EXERCITO.arma

/*
*	RETORNA 0 SE EQUIPAMENTO JA ESTA A SER UTILIZADO
*	RETORNA 1 SE ESTIVER LIVRE
*/
CREATE FUNCTION EXERCITO.equipIsAvailable (@id INT)
RETURNS BIT
AS
BEGIN
	IF EXISTS (SELECT * FROM EXERCITO.utiliza_equipamento WHERE equipamento=@id)
		RETURN 0
	RETURN 1
END


/*
*
*	RETORNA TABLE COM O CONJUNTO DE NACIONALIDADES DOS MILITARES
*/
CREATE FUNCTION EXERCITO.getNacionalidades() RETURNS @nac TABLE (id INT, nacionalidade VARCHAR(50))
AS
	BEGIN
		DECLARE @id INT
		DECLARE @nacionalidade VARCHAR(50)
		
		DECLARE cur CURSOR FAST_FORWARD 
		FOR SELECT DISTINCT nacionalidade FROM EXERCITO.militar
		OPEN cur;

		FETCH cur INTO @nacionalidade
		SELECT @id=1

		WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO @nac VALUES(@id, @nacionalidade)
				SELECT @id = @id + 1
				FETCH cur INTO @nacionalidade
			END
		CLOSE cur;
		DEALLOCATE cur;

		RETURN

	END
GO

SELECT * FROM EXERCITO.getNacionalidades()