/*
*	RETORNA 0 SE MILITAR DE nCC JA EXISTE EM SOLDADO
*	MEDICO OU ENGENHEIRO
*/
ALTER FUNCTION EXERCITO.disjointMilitar (@nCC INT)
RETURNS BIT
AS
BEGIN
	IF EXISTS (SELECT * FROM EXERCITO.soldado WHERE nCC = @nCC)
	OR EXISTS (SELECT * FROM EXERCITO.medico WHERE nCC = @nCC)
	OR EXISTS (SELECT * FROM EXERCITO.engenheiro WHERE nCC = @nCC)
		BEGIN
			RETURN 0
		END
	RETURN 1
END
GO

SELECT * FROM EXERCITO.tipo_veiculo
SELECT * FROM EXERCITO.tipo_equipamento
SELECT DISTINCT(maintipo) FROM EXERCITO.tipo_veiculo WHERE maintipo = 8 AND id=25
